name: Testing maestro

on:
  push:
    branches:
      - main

jobs:
  Echo_workflow:
    runs-on: [self-hosted]
    steps:
    - name: Contact
      run: echo Hello, world!
  Build_APK:
    needs: Echo_workflow
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build APK name
      run: ./gradlew assembleRelease
  

    
