name: Testing maestro

on:
  push:
    branches:
      - main

jobs:
  Echo_workflow:
    runs-on: [self-hosted]
    steps:
    - name: Contact
      run: echo Hello, world!
  Build_APK:
    runs-on: [self-hosted]
    steps:
    - name: Build APK name
      run: Build APK
  

    
